### ISSUE TITLE
Add support for main brush, side brush, and vacuum motors

### ISSUE THREAD

**Issue by jacobperron** [AutonomyLab/create_autonomy#15]
Add subscribers to listen for the three different motor commands.

**Comment by ghost** [comment]
Is this still in the works?

**Comment by jacobperron** [comment]
@zserlin1 I haven't had time to work on this. There was some work done on this a while ago (#36), perhaps I'll get to it one weekend. In the meantime, PRs always welcome :)

To make the API more clear for developers, I think using a custom message for controlling the motors would be good. A proposal for `ca_msgs/MotorSetpoint`:

        # For the main and side brush motors, provide a duty cycle in the range [-1, 1]
        # The range of acceptable values for the vacuum motor is [0, 1]
        float32 duty_cycle

**Comment by nnarain** [comment]
Hi. I was looking into adding a command topic for the vacuum motor. See https://github.com/nnarain/create_robot/commit/d221878e562c30f71ff88a94dc21fc7d98aecd2e

Currently implemented as a `std_msgs/Float32`. Would `create_msgs/MotorSetPoint` be preferable?

**Comment by vinnnyr** [comment]
I would prefer a `create_msgs/MotorSetPoint` since [std_msgs is in theory deprecated](https://docs.ros.org/en/foxy/Releases/Release-Foxy-Fitzroy.html#std-msgs)

**Comment by nnarain** [comment]
Was not aware of that. Thanks!

**Comment by jacobperron** [comment]
Yes, I am also in favor of a semantically meaning message (e.g. like `create_msgs/MotorSetPoint`).

**Comment by AdronTech** [comment]
Would it also be possible to merge this into the foxy branch?

**Comment by jacobperron** [comment]
Here's a port for Foxy: https://github.com/AutonomyLab/create_robot/pull/97
