### ISSUE TITLE
Add Create 1 description

### ISSUE THREAD

**Issue by jacobperron** [AutonomyLab/create_autonomy#18]
Should add URDF model and mesh for Create 1.

**Comment by lopsided98** [comment]
The [create_description](https://github.com/turtlebot/turtlebot_create/tree/indigo/create_description) project includes a mesh and URDF model (it would need some changes match the setup used in this project). I'm not sure if there are any licensing issues with borrowing it.

**Comment by lucbettaieb** [comment]
It's a BSD-licensed, so as long as you follow the BSD guidelines, you should be fine.

**Comment by jacobperron** [comment]
Done in #27
