### ISSUE TITLE
How to upgrade iRobot create_2 firmware to 3.2.6

### ISSUE THREAD

**Issue by Robert-Zwemer** [AutonomyLab/create_autonomy#39]
Not certain this is an issue, might be my ignorance, but looking for help. Have posted on the ROS Answers as well. The create_autonomy github readme indicates that the Create 2 (firmware >= 3.2.6). Been googling and contacted iRobot twice, still unable to figure how to upgrade firmware to 3.2.6. Any help in this matter will be deeply appreciated.

**Comment by jacobperron** [comment]
I've responded to you on [ROS answers](http://answers.ros.org/question/262720/how-to-upgrade-irobot-create_2-firmware-to-326/?answer=262786#post-id-262786).

Are there issues using create_autonomy with your robot?
