### ISSUE TITLE
No joy_teleop.py file

### ISSUE THREAD

**Issue by ghost** [AutonomyLab/create_autonomy#40]
I am trying to run the ca_tools joy_teleop.launch file but I am getting an error saying "cannot launch node of type [joy_teleop/joy_teleop.py]: joy_teleop. I do not see this type of file in either joy or create_autonomy. Where does it come from?

**Comment by jacobperron** [comment]
Sounds like *joy_teleop* isn't installed. From the root of the repo, try:

```sh
rosdep update
rosdep install --from-paths . -i
```
