### ISSUE TITLE
Odom topic parameters

### ISSUE THREAD

**Issue by htrinh96** [AutonomyLab/create_autonomy#49]
Hello everyone,

I'm doing a localization project using create_autonomy package. When I display topic "odom" (rostopic echo /odom), I see parameter "z" and "w" under "orientation" section. I think "z" parameter represents the angle the robot turns but I'm not sure what unit it is. The robot was turned roughly 90 degrees and "z" parameter showed around 0.7, so either the unit is not radian or the error the robot experiencing is huge. 

Please let me know what "z" and "w" parameters mean and the units of them.
Any help would be much appreciated.

Thanks

**Comment by jacobperron** [comment]
The orientation component of the odometry message is a [Quaternion](http://quaternions.online/). You can use a library like [tf2](http://wiki.ros.org/tf2) to convert Quaternions to/from Euler angles. For example, the following code snippet should get you the yaw angle:

```c
#include <tf2/utils.h>
// Assuming 'odom_msg' is of type nav_msgs/Odometry
double yaw = tf2::getYaw(odom_msg.pose.pose.orientation);
```

If you have further questions (that aren't directly issues with the create_autonomy driver) please post on [ROS Answers](answers.ros.org).
