### ISSUE TITLE
Add support for creating/playing songs

### ISSUE THREAD

**Issue by jacobperron** [AutonomyLab/create_autonomy#5]
Already supported in the underlying library (https://github.com/AutonomyLab/libcreate), just need to expose at the ROS API level.

**Comment by clydemcqueen** [comment]
Hi, are you interested in help on this? I have a simple solution up and running.

**Comment by jacobperron** [comment]
Pull requests are welcome :+1:

**Comment by clydemcqueen** [comment]
https://github.com/AutonomyLab/create_autonomy/pull/37
