### ISSUE TITLE
RESET  ODOMETRY?

### ISSUE THREAD

**Issue by epsilon11101** [AutonomyLab/create_autonomy#62]
hi , someone knows how restart odometry ?

**Comment by jacobperron** [comment]
What do you mean by "restart odometry"?

If you are looking for a way to reset the published odometry values to zero, there is no feature to do this other than restarting the driver. I think it would be reasonable to add a ROS service to trigger a reset. I'm happy to review any contributions!

**Comment by epsilon11101** [comment]
thank you :)

**Comment by epsilon11101** [comment]
this can work! : @jacobperron 

http://wiki.ros.org/navigation/Tutorials/RobotSetup/Odom
