### ISSUE TITLE
How to publish covariance for ekf

### ISSUE THREAD

**Issue by kc944201** [AutonomyLab/create_autonomy#67]
HI, I'm using a intel d435i for navigation with create 2

I want to use robot pose ekf package to combine odometry and IMU data

I have seen create_driver.cpp already publish covariance matrix 

but when I launch the robot driver, it shows the following error

[ERROR] [1594611946.458760993]: Covariance specified for measurement on topic wheelodom is zero
[ERROR] [1594611946.500368988]: filter time older than odom message buffer

Is the covariance matrix not publish to the topic?

**Comment by Bscout2011** [comment]
Hi @kc944201,
The [topic](http://docs.ros.org/en/noetic/api/nav_msgs/html/msg/Odometry.html) `/odom` has covariance information inside of it. 

Is this what you're looking for?

**Comment by kc944201** [comment]
Thank you for your reply
I have already resolved the problem.

**Comment by Krishnakanth9187** [comment]
@kc944201 how did you solve it.
