### ISSUE TITLE
No `/mode` topic or service

### ISSUE THREAD

**Issue by jacobwaller** [AutonomyLab/create_autonomy#90]
Wanted to add this myself for a project I'm working on, but do not have time at the moment.

There is no `/mode` topic or service. Or really, no way to set the current mode of the create at any given time.

**Comment by jacobperron** [comment]
Exposing this as a service sounds reasonable to me. I'm happy to review a PR adding this if you find time at some point.

**Comment by jacobperron** [comment]
Duplicate: https://github.com/AutonomyLab/create_robot/issues/13
